const poemData = [
    { text: "扁鹊", py: "biǎn què", zh: "扁鹊，战国时期著名的医学家，精通望闻问切。", en: "Bian Que" },
    { text: "见", py: "jiàn", zh: "动词，拜见，会见。", en: "visited" },
    { text: "蔡桓公", py: "cài huán gōng", zh: "蔡桓公，即蔡国的国君（文中也称桓侯）。", en: "Duke Huan of Cai," },
    { text: "，", punc: true },
    { text: "立", py: "lì", zh: "动词，站立。", en: "stood" },
    { text: "有间", py: "yǒu jiàn", zh: "时间词组，站了一会儿。", en: "for a while.", exam: true },
    { text: "。", punc: true },
    { text: "扁鹊", py: "biǎn què", zh: "扁鹊。", en: "Bian Que" },
    { text: "曰", py: "yuē", zh: "说。", en: "said," },
    { text: "：", punc: true },
    { text: "“", punc: true },
    { text: "君", py: "jūn", zh: "代词，您（对国君的尊称）。", en: "Your Majesty" },
    { text: "有", py: "yǒu", zh: "有。", en: "has a" },
    { text: "疾", py: "jí", zh: "名词，小病，微疾。", en: "sickness" },
    { text: "在", py: "zài", zh: "在。", en: "in the" },
    { text: "腠理", py: "còu lǐ", zh: "名词，中医指皮肤的纹理和皮下肌肉的交界处。", en: "skin tissue.", exam: true },
    { text: "，", punc: true },
    { text: "不", py: "bù", zh: "不。", en: "If it is not" },
    { text: "治", py: "zhì", zh: "动词，医治，治疗。", en: "treated," },
    { text: "将", py: "jiāng", zh: "副词，恐怕会，将会。", en: "it will" },
    { text: "恐", py: "kǒng", zh: "副词，恐怕，担心。", en: "probably" },
    { text: "深", py: "shēn", zh: "形容词，变深，加重。", en: "become deeper." },
    { text: "”", punc: true },
    { text: "桓侯", py: "huán hòu", zh: "蔡桓公。", en: "Duke Huan" },
    { text: "曰", py: "yuē", zh: "说。", en: "said," },
    { text: "：", punc: true },
    { text: "“", punc: true },
    { text: "寡人", py: "guǎ rén", zh: "代词，古代君主的谦称，相当于“我”。", en: "I" },
    { text: "无", py: "wú", zh: "没有。", en: "have no" },
    { text: "疾", py: "jí", zh: "疾病。", en: "sickness." },
    { text: "”", punc: true },
    { text: "扁鹊", py: "biǎn què", zh: "扁鹊。", en: "Bian Que" },
    { text: "出", py: "chū", zh: "动词，退出，离开。", en: "left." },
    { text: "，", punc: true },
    { text: "桓侯", py: "huán hòu", zh: "蔡桓公。", en: "Duke Huan" },
    { text: "曰", py: "yuē", zh: "说。", en: "said," },
    { text: "：", punc: true },
    { text: "“", punc: true },
    { text: "医", py: "yī", zh: "名词，医生。", en: "Doctors" },
    { text: "之", py: "zhī", zh: "结构助词，用在主谓之间，取消句子独立性，不译。", en: "" },
    { text: "好", py: "hào", zh: "动词，喜欢，爱好。", en: "like to", exam: true },
    { text: "治", py: "zhì", zh: "治疗。", en: "treat" },
    { text: "不病", py: "bú bìng", zh: "名词性词组，没有生病的人。", en: "healthy people" },
    { text: "以", py: "yǐ", zh: "介词，把……作为。", en: "to take" },
    { text: "为", py: "wéi", zh: "动词，作为，算作。", en: "it as their own" },
    { text: "功", py: "gōng", zh: "名词，功劳，功绩。", en: "achievement." },
    { text: "”", punc: true },
    { text: "居", py: "jū", zh: "动词，停留，这里指过了、相隔。", en: "After", exam: true },
    { text: "十日", py: "shí rì", zh: "十天。", en: "ten days," },
    { text: "，", punc: true },
    { text: "扁鹊", py: "biǎn què", zh: "扁鹊。", en: "Bian Que" },
    { text: "复", py: "fù", zh: "副词，再次，重新。", en: "again" },
    { text: "见", py: "jiàn", zh: "拜见。", en: "visited him and" },
    { text: "，", punc: true },
    { text: "曰", py: "yuē", zh: "说。", en: "said," },
    { text: "：", punc: true },
    { text: "“", punc: true },
    { text: "君", py: "jūn", zh: "您的。", en: "Your" },
    { text: "之", py: "zhī", zh: "结构助词，的。", en: "" },
    { text: "病", py: "bìng", zh: "名词，病（比‘疾’严重一些）。", en: "sickness" },
    { text: "在", py: "zài", zh: "在。", en: "is in the" },
    { text: "肌肤", py: "jī fū", zh: "名词，肌肉和皮肤。", en: "flesh," },
    { text: "，", punc: true },
    { text: "不", py: "bù", zh: "不。", en: "if not" },
    { text: "治", py: "zhì", zh: "医治。", en: "treated," },
    { text: "将", py: "jiāng", zh: "将会。", en: "it will go" },
    { text: "益", py: "yì", zh: "副词，更加、更。", en: "even", exam: true },
    { text: "深", py: "shēn", zh: "严重。", en: "deeper." },
    { text: "”", punc: true },
    { text: "桓侯", py: "huán hòu", zh: "蔡桓公。", en: "Duke Huan" },
    { text: "不", py: "bù", zh: "不。", en: "did not" },
    { text: "应", py: "yìng", zh: "动词，理睬，理会，应答。", en: "answer.", exam: true },
    { text: "。", punc: true },
    { text: "扁鹊", py: "biǎn què", zh: "扁鹊。", en: "Bian Que" },
    { text: "出", py: "chū", zh: "退出。", en: "left," },
    { text: "，", punc: true },
    { text: "桓侯", py: "huán hòu", zh: "蔡桓公。", en: "and Duke Huan" },
    { text: "又", py: "yòu", zh: "副词，再次。", en: "was once again" },
    { text: "不悦", py: "bú yuè", zh: "形容词，不高兴，不买账。", en: "unhappy." },
    { text: "。", punc: true },
    { text: "居", py: "jū", zh: "过了。", en: "After" },
    { text: "十日", py: "shí rì", zh: "十天。", en: "another ten days," },
    { text: "，", punc: true },
    { text: "扁鹊", py: "biǎn què", zh: "扁鹊。", en: "Bian Que" },
    { text: "复", py: "fù", zh: "再次。", en: "again" },
    { text: "见", py: "jiàn", zh: "拜见。", en: "visited and" },
    { text: "，", punc: true },
    { text: "曰", py: "yuē", zh: "说。", en: "said," },
    { text: "：", punc: true },
    { text: "“", punc: true },
    { text: "君", py: "jūn", zh: "您。", en: "Your" },
    { text: "之", py: "zhī", zh: "的。", en: "" },
    { text: "病", py: "bìng", zh: "病。", en: "sickness" },
    { text: "在", py: "zài", zh: "在。", en: "is in the" },
    { text: "肠胃", py: "cháng wèi", zh: "名词，肠和胃。", en: "stomach and intestines," },
    { text: "，", punc: true },
    { text: "不", py: "bù", zh: "不。", en: "if not" },
    { text: "治", py: "zhì", zh: "医治。", en: "treated," },
    { text: "将", py: "jiāng", zh: "将会。", en: "it will grow" },
    { text: "益", py: "yì", zh: "更加。", en: "even" },
    { text: "深", py: "shēn", zh: "严重。", en: "worse." },
    { text: "”", punc: true },
    { text: "桓侯", py: "huán hòu", zh: "蔡桓公。", en: "Duke Huan" },
    { text: "又", py: "yòu", zh: "再次。", en: "still did not" },
    { text: "不", py: "bù", zh: "不。", en: "" },
    { text: "应", py: "yìng", zh: "理睬。", en: "reply," },
    { text: "。", punc: true },
    { text: "扁鹊", py: "biǎn què", zh: "扁鹊。", en: "Bian Que" },
    { text: "出", py: "chū", zh: "退出。", en: "left," },
    { text: "，", punc: true },
    { text: "桓侯", py: "huán hòu", zh: "蔡桓公。", en: "and Duke Huan" },
    { text: "又", py: "yòu", zh: "又。", en: "was" },
    { text: "不悦", py: "bú yuè", zh: "不高兴。", en: "annoyed again." },
    { text: "。", punc: true },
    { text: "居", py: "jū", zh: "过了。", en: "After" },
    { text: "十日", py: "shí rì", zh: "十天。", en: "another ten days," },
    { text: "，", punc: true },
    { text: "扁鹊", py: "biǎn què", zh: "扁鹊。", en: "Bian Que" },
    { text: "望", py: "wàng", zh: "动词，远远地看，望见。", en: "looked at" },
    { text: "桓侯", py: "huán hòu", zh: "蔡桓公。", en: "Duke Huan from a distance" },
    { text: "而", py: "ér", zh: "连词，表顺接，就。", en: "and" },
    { text: "还", py: "xuán", zh: "通假字，同“旋”，副词，回转、掉转。", en: "turned", exam: true },
    { text: "走", py: "zǒu", zh: "动词，古义是小跑、跑，这里指快步跑开。", en: "around and ran away.", exam: true },
    { text: "。", punc: true },
    { text: "桓侯", py: "huán hòu", zh: "蔡桓公。", en: "Duke Huan" },
    { text: "故", py: "gù", zh: "副词，特意，故意。", en: "purposely", exam: true },
    { text: "使", py: "shǐ", zh: "动词，派遣，派人。", en: "sent" },
    { text: "人", py: "rén", zh: "人。", en: "someone to" },
    { text: "问", py: "wèn", zh: "询问。", en: "ask him why." },
    { text: "之", py: "zhī", zh: "代词，指代扁鹊跑开的原因。", en: "" },
    { text: "，", punc: true },
    { text: "扁鹊", py: "biǎn què", zh: "扁鹊。", en: "Bian Que" },
    { text: "曰", py: "yuē", zh: "说。", en: "said," },
    { text: "：", punc: true },
    { text: "“", punc: true },
    { text: "疾", py: "jí", zh: "小病。", en: "When the sickness" },
    { text: "在", py: "zài", zh: "在。", en: "is in the" },
    { text: "腠理", py: "còu lǐ", zh: "皮肤纹理。", en: "skin tissue," },
    { text: "，", punc: true },
    { text: "汤熨", py: "tàng wèi", zh: "名词作动词，用热水药热敷治疗。", en: "hot herbal compresses", exam: true },
    { text: "之", py: "zhī", zh: "结构助词，不译。", en: "" },
    { text: "所", py: "suǒ", zh: "特殊助词，与及结合表示……的范围。", en: "can" },
    { text: "及", py: "jí", zh: "动词，达到，达到治疗效果。", en: "reach and treat it;" },
    { text: "也", py: "yě", zh: "判断语气词。", en: "" },
    { text: "；", punc: true },
    { text: "在", py: "zài", zh: "在。", en: "when it is in the" },
    { text: "肌肤", py: "jī fū", zh: "肌肉皮肤。", en: "flesh," },
    { text: "，", punc: true },
    { text: "针石", py: "zhēn shí", zh: "名词作动词，用金属针和石针刺穴位治疗。", en: "acupuncture and stone needles", exam: true },
    { text: "之", py: "zhī", zh: "助词。", en: "" },
    { text: "所", py: "suǒ", zh: "助词。", en: "can" },
    { text: "及", py: "jí", zh: "达到。", en: "reach it;" },
    { text: "也", py: "yě", zh: "语气词。", en: "" },
    { text: "；", punc: true },
    { text: "在", py: "zài", zh: "在。", en: "when it is in the" },
    { text: "肠胃", py: "cháng wèi", zh: "肠胃。", en: "stomach and intestines," },
    { text: "，", punc: true },
    { text: "火齐", py: "huǒ jì", zh: "名词，一种中医汤药剂（火齐汤）。", en: "herbal soups", exam: true },
    { text: "之", py: "zhī", zh: "助词。", en: "" },
    { text: "所", py: "suǒ", zh: "助词。", en: "can" },
    { text: "及", py: "jí", zh: "达到。", en: "reach it;" },
    { text: "也", py: "yě", zh: "语气词。", en: "" },
    { text: "；", punc: true },
    { text: "在", py: "zài", zh: "在。", en: "but once it reaches the" },
    { text: "骨髓", py: "gǔ suǐ", zh: "名词，骨头深处的骨髓。", en: "bone marrow," },
    { text: "，", punc: true },
    { text: "司命", py: "sī mìng", zh: "名词，传说中掌管人类寿命的神。", en: "it is the department of the God of Fate," },
    { text: "之", py: "zhī", zh: "的。", en: "" },
    { text: "所属", py: "suǒ shǔ", zh: "动词词组，管辖的范围。", en: "" },
    { text: "，", punc: true },
    { text: "无奈何", py: "wú nài hé", zh: "固定词组，对此没有任何办法。", en: "and there is nothing we can do.", exam: true },
    { text: "也", py: "yě", zh: "语气词。", en: "" },
    { text: "。", punc: true },
    { text: "今", py: "jīn", zh: "现在。", en: "Now the sickness is" },
    { text: "在", py: "zài", zh: "在。", en: "in the" },
    { text: "骨髓", py: "gǔ suǐ", zh: "骨髓深处。", en: "bone marrow," },
    { text: "，", punc: true },
    { text: "臣", py: "chén", zh: "代词，微臣（扁鹊自称）。", en: "so I" },
    { text: "是以前", py: "shì yǐ wéi", zh: "这里写成“是以无请也”：是以，因此；无请，不再询问、不再申请治疗。", en: "did not ask to treat him again.", exam: true },
    { text: "也", py: "yě", zh: "语气词。", en: "" },
    { text: "重", py: "”", zh: "”", en: "”" }, // 确保清除混入词
    { text: "已", py: "yǐ", zh: "副词，已经。", en: "After" },
    { text: "居", py: "jū", zh: "过了。", en: "" },
    { text: "五日", py: "wǔ rì", zh: "五天。", en: "five days," },
    { text: "，", punc: true },
    { text: "桓侯", py: "huán hòu", zh: "蔡桓公。", en: "Duke Huan" },
    { text: "体痛", py: "tǐ tòng", zh: "动词短语，身体开始剧烈疼痛。", en: "felt pain in his body." },
    { text: "，", punc: true },
    { text: "使", py: "shǐ", zh: "派遣。", en: "He sent" },
    { text: "人", py: "rén", zh: "人。", en: "men to" },
    { text: "索", py: "suǒ", zh: "动词，寻找，搜寻。", en: "search for", exam: true },
    { text: "扁鹊", py: "biǎn què", zh: "扁鹊。", en: "Bian Que," },
    { text: "，", punc: true },
    { text: "已", py: "yǐ", zh: "已经。", en: "but Bian Que had already" },
    { text: "逃", py: "táo", zh: "逃跑去。", en: "escaped to" },
    { text: "秦", py: "qín", zh: "秦国。", en: "the State of Qin." },
    { text: "矣", py: "yǐ", zh: "文言句末语气词，表示事情已经发生。", en: "" },
    { text: "。", punc: true },
    { text: "桓侯", py: "huán hòu", zh: "蔡桓公。", en: "Duke Huan" },
    { text: "遂", py: "suì", zh: "副词，于是，就。", en: "then" },
    { text: "死", py: "sǐ", zh: "死去了。", en: "died." },
    { text: "。", punc: true }
];
